// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	TIMEZONE: string;
	GITHUB_USERNAME: string;
	GITHUB_TOKEN: string;
	REMINDER_HOURS: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_CHAT_ID: string;
}