// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	TIMEZONE: string;
	GITHUB_USERNAME: string;
	GITHUB_TOKEN: string;
	EMAIL_RECIPIENT: string;
	SENDER_EMAIL: string;
	REMINDER_HOURS: string;
	REMINDER_SUBJECTS: string;
	REMINDER_BODIES: string;
}
